# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_Historyresult = QtWidgets.QTableWidget(Form)
        self.tableWidget_Historyresult.setObjectName("tableWidget_Historyresult")
        self.tableWidget_Historyresult.setColumnCount(0)
        self.tableWidget_Historyresult.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_Historyresult, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tableWidget_Historyresult.itemDoubleClicked['QTableWidgetItem*'].connect(Form.s_open_url)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "History"))
